name: Validate Development for Release

on:
  push:
    branches: ["development"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDk
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change permissions of Wrapper
        run: chmod +x ./gradlew

      - name: Decode BASEURL
        env:
          BASEURL: ${{ secrets.BASEURL }}
        run: echo BASEURL="$BASEURL" > ./local.properties

      - name: Clean Project
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew build